/* Drawescape V6 - stable interactive prototype
   No build step. Canvas fallback first; optional Three.js WebGL loaded on demand.
*/
const $ = (id)=>document.getElementById(id);
const TAU = Math.PI*2;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const lerp=(a,b,t)=>a+(b-a)*t;
const rand=(a,b)=>a+Math.random()*(b-a);
function go(id){document.getElementById(id)?.scrollIntoView({behavior:'smooth',block:'start'});} window.go=go;
function toast(msg){const t=$('toast'); t.textContent=msg; t.hidden=false; clearTimeout(toast._t); toast._t=setTimeout(()=>t.hidden=true,2200);} window.toast=toast;
function toggleFocus(){document.body.classList.toggle('focus'); toast(document.body.classList.contains('focus')?'聚焦模式开启':'聚焦模式关闭');} window.toggleFocus=toggleFocus;
function resetProgress(){localStorage.removeItem('drawescape_views_v6');localStorage.removeItem('drawescape_perspective_v6');toast('本地进度已重置');refreshSavedViews();} window.resetProgress=resetProgress;
function hexToRgb(hex){const h=hex.replace('#','');return {r:parseInt(h.slice(0,2),16),g:parseInt(h.slice(2,4),16),b:parseInt(h.slice(4,6),16)}}
function rgbToHex(r,g,b){return '#'+[r,g,b].map(v=>clamp(Math.round(v),0,255).toString(16).padStart(2,'0')).join('')}
function mix(c1,c2,t){return {r:lerp(c1.r,c2.r,t),g:lerp(c1.g,c2.g,t),b:lerp(c1.b,c2.b,t)}}
function canvasPoint(canvas,e){const r=canvas.getBoundingClientRect();const p=e.touches?e.touches[0]:e;return {x:(p.clientX-r.left)*canvas.width/r.width,y:(p.clientY-r.top)*canvas.height/r.height};}
function downloadBlob(name,content,type='application/json'){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([content],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function exportCanvas(id,name){const c=$(id); const a=document.createElement('a'); a.href=c.toDataURL('image/png'); a.download=name; a.click();} window.exportCanvas=exportCanvas;

// ---------------- cover animation ----------------
function cover(){const c=$('coverCanvas'),ctx=c.getContext('2d');let t=0;function frame(){t+=0.012;const w=c.width,h=c.height;ctx.clearRect(0,0,w,h);let g=ctx.createLinearGradient(0,0,w,h);g.addColorStop(0,'#172438');g.addColorStop(.5,'#3f6ea4');g.addColorStop(1,'#ffe0a0');ctx.fillStyle=g;ctx.fillRect(0,0,w,h);ctx.globalAlpha=.75;ctx.strokeStyle='rgba(255,255,255,.16)';ctx.lineWidth=1;for(let x=-80;x<w+80;x+=48){ctx.beginPath();ctx.moveTo(x+Math.sin(t+x*.01)*18,0);ctx.lineTo(x+140+Math.sin(t+x*.008)*25,h);ctx.stroke();}for(let y=20;y<h;y+=42){ctx.beginPath();ctx.moveTo(0,y+Math.sin(t+y*.02)*8);ctx.lineTo(w,y+Math.cos(t+y*.02)*10);ctx.stroke();}ctx.globalAlpha=1;
    const cx=w*.5, cy=h*.52; const yaw=Math.sin(t)*.65; const pts=[[-95,-70,80],[95,-70,80],[95,70,80],[-95,70,80],[-95,-70,-80],[95,-70,-80],[95,70,-80],[-95,70,-80]];
    const proj=pts.map(p=>{let [x,y,z]=p;let x2=x*Math.cos(yaw)-z*Math.sin(yaw), z2=x*Math.sin(yaw)+z*Math.cos(yaw);let s=440/(440+z2);return {x:cx+x2*s,y:cy+y*s,z:z2};});
    const edges=[[0,1],[1,2],[2,3],[3,0],[4,5],[5,6],[6,7],[7,4],[0,4],[1,5],[2,6],[3,7]];ctx.lineWidth=2.4;ctx.strokeStyle='rgba(255,255,255,.72)';edges.forEach(e=>{ctx.beginPath();ctx.moveTo(proj[e[0]].x,proj[e[0]].y);ctx.lineTo(proj[e[1]].x,proj[e[1]].y);ctx.stroke();});
    ctx.fillStyle='rgba(255,209,102,.95)';proj.forEach(p=>{ctx.beginPath();ctx.arc(p.x,p.y,4,0,TAU);ctx.fill();});
    ctx.strokeStyle='rgba(95,213,204,.75)';ctx.lineWidth=1.4;for(let i=0;i<7;i++){ctx.beginPath();let y=cy-130+i*38;ctx.moveTo(70,y+Math.sin(t+i)*10);ctx.bezierCurveTo(220,y-40,430,y+40,560,y+Math.cos(t+i)*10);ctx.stroke();}
    ctx.fillStyle='rgba(255,255,255,.88)';ctx.font='700 18px system-ui';ctx.fillText('2D drawing ←→ 3D world model',42,h-38);requestAnimationFrame(frame)}frame();}

// ---------------- data ----------------
const pipeline=[
 {id:'observe',icon:'👁️',title:'观察 Observe',core:'收集信息，不急着画',code:'image → features',text:'先看锚点、比例、遮挡、光源，不被细节淹没。'},
 {id:'scan',icon:'🔎',title:'拆层 Scan',core:'把一张图拆成通道',code:'depth / normal / albedo',text:'深度、法线、固有色、光照、材质分开看。'},
 {id:'align',icon:'📍',title:'对齐 Align',core:'保持坐标系一致',code:'points → coordinates',text:'中心线、视平线、消失点、骨点都属于同一坐标系统。'},
 {id:'model',icon:'🧊',title:'建模 Model',core:'用几何代理复杂世界',code:'box + sphere + cylinder',text:'人、树、衣服、水都先用简化体块和力场理解。'},
 {id:'render',icon:'💡',title:'渲染 Render',core:'让光和材质进入模型',code:'diffuse + specular + AO',text:'明暗交界线、高光、反光、AO 分开判断。'},
 {id:'fold',icon:'🌀',title:'折叠 Fold',core:'把三维压成二维',code:'projection + selection',text:'透视是投影，风格是选择保留哪些信息。'},
 {id:'style',icon:'🎭',title:'风格 Style',core:'感受变成参数',code:'line / color / contrast',text:'线条粗细、色彩温度、明暗对比、比例变形都在表达情绪。'},
 {id:'calibrate',icon:'⭐',title:'校准 Calibrate',core:'比对、修正、积累经验',code:'prediction ↔ feedback',text:'画错不是失败，是内部模型在更新。'}
];
const zones=[
 {id:'line',x:105,y:120,c:'#5fd5cc',name:'线之海',en:'Topology',pain:'线条总像贴在纸上',lab:'worldlab',core:'线不是边框，而是面转折、深度不连续和结构关系。'},
 {id:'ratio',x:285,y:190,c:'#ffd166',name:'比例森林',en:'Relations',pain:'不看参考就比例乱',lab:'facelab',core:'比例是坐标点之间的相对关系，不是孤立长度。'},
 {id:'camera',x:480,y:110,c:'#4da8d8',name:'相机塔',en:'Perspective',pain:'透视规则背了也不会用',lab:'perspective',core:'透视是相机模型。视平线、焦距和消失点共同决定投影。'},
 {id:'depth',x:670,y:190,c:'#8d7bea',name:'深度湖',en:'Depth map',pain:'阴影和空间混在一起',lab:'lightlab',core:'深度只表示远近，阴影表示光照关系。先拆开再合成。'},
 {id:'light',x:870,y:120,c:'#f2a7b5',name:'光之月台',en:'Normal & light',pain:'明暗交界线总画不准',lab:'lightlab',core:'交界线来自表面法线与光线夹角，是几何边界。'},
 {id:'material',x:1035,y:260,c:'#8ebf91',name:'材质星市',en:'Material',pain:'颜色和质感不真实',lab:'lightlab',core:'固有色、粗糙度、金属度、菲涅尔、高光和环境反光要分通道。'},
 {id:'folds',x:785,y:410,c:'#e7a666',name:'褶皱剧场',en:'Force',pain:'衣服、头发、风都乱',lab:'foldlab',core:'先找固定点、张力方向、材料硬度，再画线条节奏。'},
 {id:'face',x:525,y:440,c:'#e76f6f',name:'人脸星图',en:'Face model',pain:'人脸结构和彩色明暗容易错',lab:'facelab',core:'头部是三维代理模型：中心线、眼线、面块、五官锚点必须同步变化。'},
 {id:'style',x:260,y:420,c:'#c7a2ff',name:'折叠云城',en:'Style',pain:'很难表达自己的内心',lab:'stylelab',core:'风格是信息压缩策略：保留什么、夸张什么、弱化什么。'}
];
const sources=[
 ['透视与成像','线性透视、针孔相机、正交/轴测投影','欧洲学院派透视训练、建筑制图、计算机图形学相机模型'],
 ['计算机视觉','关键点、对齐、三角测量、深度估计','把“画不准”转成坐标点匹配和误差校准'],
 ['计算机图形学','深度图、法线、BRDF、漫反射、高光、AO','把光影和材质拆成可视通道'],
 ['建模软件','Blender / Rhino / SketchUp 的体块、推拉、旋转体、扫掠','把线稿理解成模型操作'],
 ['传统绘画','Loomis 头部、结构素描、解剖、褶皱、色彩理论','把经验知识翻译成可互动的结构练习'],
 ['认知与 ND 设计','低负荷、分层、可视反馈、短关卡、无羞辱校准','帮助学习者把模糊挫败变成具体可修正的信息']
];
const emotions=[
 ['安静','低对比、慢线条、远距离、低饱和','线条轻；边缘软；背景留白多'],
 ['紧张','斜线、强透视、高对比、压迫构图','视角低/近；阴影硬；形体压缩'],
 ['温暖','暖光、圆形、低锐度、中高明度','减少黑色；让边缘反光更柔'],
 ['孤独','大空间、小人物、冷色、低饱和','把人物放在远离中心的空白里'],
 ['勇气','上升线、稳定三角、清晰轮廓、强光源','姿态打开；边缘硬；对比更明确'],
 ['梦','不完全透视、柔边缘、渐变、重复节奏','允许空间不完全真实，但内部关系要一致']
];
function renderPipeline(){ $('pipelineGrid').innerHTML=pipeline.map(p=>`<article class="pipe-card"><b>${p.icon} ${p.title}</b><p><strong>${p.core}</strong></p><code>${p.code}</code><p>${p.text}</p></article>`).join('');}
function renderSources(){ $('sourceGrid').innerHTML=sources.map(s=>`<article class="source"><b>${s[0]}</b><small>${s[1]}</small><div class="chips"><span class="chip">${s[2]}</span></div></article>`).join(''); $('emotionGrid').innerHTML=emotions.map(e=>`<article class="emotion"><b>${e[0]}</b><small>${e[1]}</small><div class="chips"><span class="chip">${e[2]}</span></div></article>`).join('');}
function renderMap(){const svg=$('worldMap');let links='';for(let i=0;i<zones.length-1;i++){links+=`<path class="map-link" d="M${zones[i].x},${zones[i].y} C${(zones[i].x+zones[i+1].x)/2},${zones[i].y-60} ${(zones[i].x+zones[i+1].x)/2},${zones[i+1].y+60} ${zones[i+1].x},${zones[i+1].y}"/>`}let nodes=zones.map(z=>`<g class="map-node" onclick="selectZone('${z.id}')"><circle cx="${z.x}" cy="${z.y}" r="54" fill="${z.c}" opacity=".9"/><text x="${z.x}" y="${z.y-6}" text-anchor="middle" font-size="20">${z.name}</text><text x="${z.x}" y="${z.y+22}" text-anchor="middle" font-size="13">${z.en}</text></g>`).join('');svg.innerHTML=`<rect x="20" y="20" width="1160" height="580" rx="36" fill="rgba(255,255,255,.36)" stroke="rgba(43,52,60,.10)"/>${links}${nodes}`;selectZone('camera');}
function selectZone(id){const z=zones.find(x=>x.id===id)||zones[0];$('mapInspector').innerHTML=`<p class="eyebrow">${z.en}</p><h3>${z.name}</h3><p><b>痛点：</b>${z.pain}</p><p><b>核心：</b>${z.core}</p><div class="chips"><span class="chip">原理</span><span class="chip">互动</span><span class="chip">纸上练习</span></div><button class="primary" onclick="go('${z.lab}')">进入对应实验</button>`;} window.selectZone=selectZone;

// ---------------- world / 3D lab ----------------
let world={objects:[],selected:null,mode:'fallback',three:null,scene:null,camera:null,renderer:null,light:null,drag:null,raycaster:null,mouse:null,plane:null};
let objSeq=1;
function updateSelect(){const s=$('worldSelect');s.innerHTML=world.objects.map(o=>`<option value="${o.id}" ${o.id===world.selected?'selected':''}>${o.name}</option>`).join('');}
function addWorldShape(type){const id='obj'+(objSeq++); const obj={id,type,name:type+' '+id,x:rand(-1.4,1.4),y:rand(-.8,.8),z:0,scale:1,rot:0,color:$('worldBaseColor')?.value||'#f3b2a6'}; if(type==='room'){obj.x=0;obj.y=0;obj.scale=1.4} world.objects.push(obj); world.selected=id; if(world.mode==='three'&&world.three) createThreeMesh(obj); updateSelect(); renderFallbackWorld(); updateWorldLesson(); toast('已添加 '+type);} window.addWorldShape=addWorldShape;
function selectWorldObject(id){world.selected=id; if(world.mode==='three') markThreeSelection(); renderFallbackWorld(); updateWorldLesson();} window.selectWorldObject=selectWorldObject;
function deleteSelectedWorldObject(){if(!world.selected){toast('没有选中对象');return} const id=world.selected; const obj=world.objects.find(o=>o.id===id); if(obj?.mesh && world.scene) world.scene.remove(obj.mesh); world.objects=world.objects.filter(o=>o.id!==id); world.selected=world.objects[0]?.id||null; updateSelect(); renderFallbackWorld(); updateWorldLesson(); toast('已删除选中几何');} window.deleteSelectedWorldObject=deleteSelectedWorldObject;
function duplicateSelectedWorldObject(){const o=world.objects.find(x=>x.id===world.selected); if(!o)return; const n={...o,id:'obj'+(objSeq++),name:o.type+' copy',x:o.x+.35,y:o.y+.22,mesh:null}; world.objects.push(n); world.selected=n.id; if(world.mode==='three') createThreeMesh(n); updateSelect(); renderFallbackWorld(); updateWorldLesson();} window.duplicateSelectedWorldObject=duplicateSelectedWorldObject;
function updateWorldLesson(){const o=world.objects.find(x=>x.id===world.selected); $('worldLesson').innerHTML=o?`<b>选中：</b>${o.name}<br><b>绘画翻译：</b>${shapeLesson(o.type)}<br><br><b>检查：</b>先用几何代理确定体块和朝向，再用材质参数决定明暗和高光。不要先画细节。`:'<b>提示：</b>添加一个形体，拖动它，把线稿理解为模型操作。';}
function shapeLesson(t){return {box:'盒体适合房间、头部平面、躯干、家具。检查透视一致性。',sphere:'球适合头颅、关节、苹果、云团。重点看法线和明暗交界线。',cylinder:'圆柱适合手臂、杯子、树干。检查椭圆与轴线。',cone:'圆锥适合鼻子、屋顶、裙摆概括。',ribbon:'飘带适合头发、布料、水流路径。看固定点和力场。',room:'房间帮助理解一点/两点透视和空间包围感。'}[t]||'几何代理帮助把复杂对象转成可计算结构。'}
function updateCameraControls(){if(world.mode==='three'&&world.camera) updateThreeCamera(); renderFallbackWorld();} window.updateCameraControls=updateCameraControls;
function updateWorldMaterial(){if(world.mode==='three'){world.objects.forEach(o=>{if(o.mesh&&o.mesh.material){o.mesh.material.color.set($('worldBaseColor').value);o.mesh.material.roughness=+$('roughness').value/100;o.mesh.material.metalness=+$('metalness').value/100;o.mesh.material.wireframe=$('wireToggle').checked;o.mesh.material.needsUpdate=true;}}); if(world.light){const a=(+$('worldLight').value)*Math.PI/180;world.light.position.set(Math.cos(a)*5,4,Math.sin(a)*5)}} renderFallbackWorld();renderShadingLab();} window.updateWorldMaterial=updateWorldMaterial;
function renderFallbackWorld(){const c=$('fallback3D'),ctx=c.getContext('2d'),w=c.width,h=c.height;ctx.clearRect(0,0,w,h);let g=ctx.createLinearGradient(0,0,w,h);g.addColorStop(0,'#eff8f8');g.addColorStop(1,'#fff4df');ctx.fillStyle=g;ctx.fillRect(0,0,w,h);const yaw=+$('camYaw').value*Math.PI/180,pitch=+$('camPitch').value*Math.PI/180,fov=+$('camFov').value;ctx.strokeStyle='rgba(77,168,216,.28)';ctx.lineWidth=1;const vp={x:w/2+Math.sin(yaw)*160,y:h*.52-Math.sin(pitch)*130};for(let x=-400;x<w+500;x+=55){ctx.beginPath();ctx.moveTo(x,h);ctx.lineTo(vp.x,vp.y);ctx.stroke()}for(let y=80;y<h;y+=55){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y+Math.sin(yaw)*30);ctx.stroke()}ctx.fillStyle='rgba(37,49,58,.8)';ctx.font='700 14px system-ui';ctx.fillText('2.5D fallback：拖动形体；加载 WebGL 后可真实 3D',18,30);
  const light=(+$('worldLight').value)*Math.PI/180; const base=hexToRgb($('worldBaseColor').value); const rough=+$('roughness').value/100;
  function project(o){const sx=w/2+o.x*150*Math.cos(yaw)+o.z*80*Math.sin(yaw);const sy=h/2-o.y*130+o.z*70*Math.sin(pitch);const s=(1.15-o.z*.08)*(60+fov)/105*o.scale;return {sx,sy,s};}
  world.objects.forEach(o=>{const p=project(o);ctx.save();ctx.translate(p.sx,p.sy);ctx.rotate(o.rot);ctx.globalAlpha=o.id===world.selected?1:.78;const shade=Math.max(.25,.65+.35*Math.cos(light-o.x));const fill=rgbToHex(base.r*shade,base.g*shade,base.b*shade);ctx.fillStyle=fill;ctx.strokeStyle=o.id===world.selected?'#ffd166':'#263240';ctx.lineWidth=o.id===world.selected?4:2;if(o.type==='box'||o.type==='room'){let bw=p.s*(o.type==='room'?2.4:1.4),bh=p.s*(o.type==='room'?1.35:1);ctx.fillRect(-bw/2,-bh/2,bw,bh);ctx.strokeRect(-bw/2,-bh/2,bw,bh);ctx.strokeStyle='rgba(38,50,64,.35)';ctx.beginPath();ctx.moveTo(-bw/2,-bh/2);ctx.lineTo(-bw/2+p.s*.45,-bh/2-p.s*.45);ctx.lineTo(bw/2+p.s*.45,-bh/2-p.s*.45);ctx.lineTo(bw/2,-bh/2);ctx.stroke();}
    else if(o.type==='sphere'){let rg=p.s*.78;let grd=ctx.createRadialGradient(-rg*.35,-rg*.45,rg*.05,0,0,rg);grd.addColorStop(0,'#fff8d6');grd.addColorStop(.35,fill);grd.addColorStop(1,'#5e5960');ctx.fillStyle=grd;ctx.beginPath();ctx.arc(0,0,rg,0,TAU);ctx.fill();ctx.stroke();}
    else if(o.type==='cylinder'){let rw=p.s*.62,rh=p.s*1.35;ctx.beginPath();ctx.ellipse(0,-rh/2,rw,rw*.28,0,0,TAU);ctx.fill();ctx.stroke();ctx.fillRect(-rw,-rh/2,rw*2,rh);ctx.strokeRect(-rw,-rh/2,rw*2,rh);ctx.beginPath();ctx.ellipse(0,rh/2,rw,rw*.28,0,0,TAU);ctx.fill();ctx.stroke();}
    else if(o.type==='cone'){ctx.beginPath();ctx.moveTo(0,-p.s);ctx.lineTo(p.s*.8,p.s*.75);ctx.lineTo(-p.s*.8,p.s*.75);ctx.closePath();ctx.fill();ctx.stroke();ctx.beginPath();ctx.ellipse(0,p.s*.75,p.s*.8,p.s*.22,0,0,TAU);ctx.stroke();}
    else {ctx.beginPath();for(let i=0;i<80;i++){const t=i/79;const x=(t-.5)*p.s*2.2;const y=Math.sin(t*TAU*1.4+o.x)*p.s*.25+t*p.s*.75; if(i===0)ctx.moveTo(x,y);else ctx.lineTo(x,y);}ctx.lineWidth=9-rough*5;ctx.strokeStyle=fill;ctx.stroke();ctx.lineWidth=2;ctx.strokeStyle=o.id===world.selected?'#ffd166':'#263240';ctx.stroke();}
    ctx.restore();});}
function fallbackHit(pt){const c=$('fallback3D'),w=c.width,h=c.height;let best=null,bd=9999;world.objects.forEach(o=>{const sx=w/2+o.x*150,sy=h/2-o.y*130,d=Math.hypot(pt.x-sx,pt.y-sy);if(d<80&&d<bd){best=o;bd=d}});return best;}
function bindFallbackDrag(){const c=$('fallback3D');let drag=null;c.addEventListener('pointerdown',e=>{const p=canvasPoint(c,e);const o=fallbackHit(p);if(o){drag={id:o.id,dx:p.x-(c.width/2+o.x*150),dy:p.y-(c.height/2-o.y*130)};world.selected=o.id;updateSelect();renderFallbackWorld();}});c.addEventListener('pointermove',e=>{if(!drag)return;const p=canvasPoint(c,e);const o=world.objects.find(x=>x.id===drag.id);o.x=(p.x-drag.dx-c.width/2)/150;o.y=-(p.y-drag.dy-c.height/2)/130;renderFallbackWorld();});window.addEventListener('pointerup',()=>drag=null);}
async function loadThreeLab(){ if(world.mode==='three'){toast('WebGL 已经运行');return} $('webglStatus').textContent='正在加载 Three.js...'; try{const THREE=await import('https://unpkg.com/three@0.160.0/build/three.module.js'); initThree(THREE); toast('WebGL 实验室已启动');}catch(e){console.warn(e);$('webglStatus').textContent='Three.js CDN 加载失败，保持 2.5D 引擎。上传 GitHub Pages 或使用网络环境再试。';toast('WebGL 加载失败，但其他互动可用');}} window.loadThreeLab=loadThreeLab;
function initThree(THREE){world.three=THREE;world.mode='three';$('fallback3D').style.display='none';const host=$('threeViewport');host.innerHTML='';world.scene=new THREE.Scene();world.scene.background=new THREE.Color(0xf2faf9);world.camera=new THREE.PerspectiveCamera(48,host.clientWidth/host.clientHeight,0.1,100);world.renderer=new THREE.WebGLRenderer({antialias:true,preserveDrawingBuffer:true});world.renderer.setPixelRatio(Math.min(devicePixelRatio,2));world.renderer.setSize(host.clientWidth,host.clientHeight);host.appendChild(world.renderer.domElement);world.light=new THREE.DirectionalLight(0xffffff,1.25);world.scene.add(world.light);world.scene.add(new THREE.HemisphereLight(0xffffff,0x88aacc,.75));const grid=new THREE.GridHelper(8,16,0x88b7bf,0xd0e4e1);world.scene.add(grid);world.raycaster=new THREE.Raycaster();world.mouse=new THREE.Vector2();world.plane=new THREE.Plane(new THREE.Vector3(0,1,0),0);world.objects.forEach(createThreeMesh);if(!world.objects.length)addWorldShape('box');updateThreeCamera();updateWorldMaterial();bindThreeDrag();function animate(){requestAnimationFrame(animate);world.renderer.render(world.scene,world.camera)}animate();window.addEventListener('resize',()=>{world.camera.aspect=host.clientWidth/host.clientHeight;world.camera.updateProjectionMatrix();world.renderer.setSize(host.clientWidth,host.clientHeight)});$('webglStatus').textContent='WebGL 已运行：点击/拖动物体；可删除、保存视角、截图。';}
function createThreeMesh(o){const THREE=world.three;if(!THREE||!world.scene)return;let geo;if(o.type==='sphere')geo=new THREE.SphereGeometry(.55,32,18);else if(o.type==='cylinder')geo=new THREE.CylinderGeometry(.45,.45,1.25,32);else if(o.type==='cone')geo=new THREE.ConeGeometry(.55,1.25,32);else if(o.type==='ribbon'){geo=new THREE.TorusKnotGeometry(.45,.09,80,8,1,3)}else if(o.type==='room')geo=new THREE.BoxGeometry(2.4,1.35,1.8);else geo=new THREE.BoxGeometry(1,1,1);const mat=new THREE.MeshStandardMaterial({color:$('worldBaseColor').value,roughness:+$('roughness').value/100,metalness:+$('metalness').value/100,wireframe:$('wireToggle').checked});const mesh=new THREE.Mesh(geo,mat);mesh.position.set(o.x,0.5+o.y,o.z);mesh.userData.id=o.id;world.scene.add(mesh);o.mesh=mesh;markThreeSelection();}
function markThreeSelection(){if(!world.three)return;world.objects.forEach(o=>{if(o.mesh){o.mesh.scale.setScalar(o.id===world.selected?1.13:1);}})}
function updateThreeCamera(){const THREE=world.three;if(!THREE||!world.camera)return;const yaw=+$('camYaw').value*Math.PI/180,pitch=+$('camPitch').value*Math.PI/180,dist=6;world.camera.fov=+$('camFov').value;world.camera.position.set(Math.sin(yaw)*dist,2.8+Math.sin(pitch)*2.2,Math.cos(yaw)*dist);world.camera.lookAt(0,0.4,0);world.camera.updateProjectionMatrix();}
function bindThreeDrag(){const canvas=world.renderer.domElement;let drag=null;canvas.addEventListener('pointerdown',e=>{const r=canvas.getBoundingClientRect();world.mouse.x=((e.clientX-r.left)/r.width)*2-1;world.mouse.y=-((e.clientY-r.top)/r.height)*2+1;world.raycaster.setFromCamera(world.mouse,world.camera);const hits=world.raycaster.intersectObjects(world.objects.map(o=>o.mesh).filter(Boolean));if(hits[0]){const id=hits[0].object.userData.id;world.selected=id;updateSelect();markThreeSelection();drag={id};canvas.setPointerCapture(e.pointerId);}});canvas.addEventListener('pointermove',e=>{if(!drag)return;const THREE=world.three,r=canvas.getBoundingClientRect();world.mouse.x=((e.clientX-r.left)/r.width)*2-1;world.mouse.y=-((e.clientY-r.top)/r.height)*2+1;world.raycaster.setFromCamera(world.mouse,world.camera);const pt=new THREE.Vector3();world.raycaster.ray.intersectPlane(world.plane,pt);const o=world.objects.find(x=>x.id===drag.id);if(o&&o.mesh){o.x=pt.x;o.z=pt.z;o.mesh.position.x=pt.x;o.mesh.position.z=pt.z;}});window.addEventListener('pointerup',()=>drag=null)}
function saveWorldSnapshot(){const views=JSON.parse(localStorage.getItem('drawescape_views_v6')||'[]');views.push({name:'view '+(views.length+1),date:new Date().toLocaleString(),yaw:+$('camYaw').value,pitch:+$('camPitch').value,fov:+$('camFov').value,objects:world.objects.map(o=>({id:o.id,type:o.type,name:o.name,x:o.x,y:o.y,z:o.z,scale:o.scale,color:o.color}))});localStorage.setItem('drawescape_views_v6',JSON.stringify(views));refreshSavedViews();toast('已保存视角与场景');} window.saveWorldSnapshot=saveWorldSnapshot;
function refreshSavedViews(){const sel=$('savedViews');if(!sel)return;const views=JSON.parse(localStorage.getItem('drawescape_views_v6')||'[]');sel.innerHTML='<option value="">选择保存视角</option>'+views.map((v,i)=>`<option value="${i}">${v.name} · ${v.date}</option>`).join('');}
function restoreWorldSnapshot(i){if(i==='')return;const v=JSON.parse(localStorage.getItem('drawescape_views_v6')||'[]')[+i];if(!v)return;$('camYaw').value=v.yaw;$('camPitch').value=v.pitch;$('camFov').value=v.fov;if(Array.isArray(v.objects)){if(world.mode==='three'&&world.scene){world.objects.forEach(o=>o.mesh&&world.scene.remove(o.mesh));}world.objects=v.objects.map(o=>({...o,mesh:null}));world.selected=world.objects[0]?.id||null;if(world.mode==='three')world.objects.forEach(createThreeMesh);updateSelect();}updateCameraControls();renderFallbackWorld();toast('已恢复视角');} window.restoreWorldSnapshot=restoreWorldSnapshot;
function exportWorldShot(){if(world.mode==='three'&&world.renderer){const a=document.createElement('a');a.href=world.renderer.domElement.toDataURL('image/png');a.download='drawescape_webgl_view.png';a.click();}else exportCanvas('fallback3D','drawescape_25d_view.png');} window.exportWorldShot=exportWorldShot;
function exportWorldJSON(){downloadBlob('drawescape_scene.json',JSON.stringify({camera:{yaw:+$('camYaw').value,pitch:+$('camPitch').value,fov:+$('camFov').value},objects:world.objects},null,2));} window.exportWorldJSON=exportWorldJSON;

// ---------------- perspective canvas ----------------
let persp={mode:'two',vp1:{x:210,y:250},vp2:{x:790,y:245},vp3:{x:520,y:-260},horizon:250,drag:null,strokes:[],drawing:null};
function setPerspectiveMode(m){persp.mode=m;drawPerspective();toast(m+' 透视模式');} window.setPerspectiveMode=setPerspectiveMode;
function drawPerspective(){const c=$('perspectiveCanvas'),ctx=c.getContext('2d'),w=c.width,h=c.height;ctx.clearRect(0,0,w,h);ctx.fillStyle='#fffaf1';ctx.fillRect(0,0,w,h);ctx.lineWidth=1;ctx.strokeStyle='rgba(38,50,64,.12)';for(let x=0;x<w;x+=40){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,h);ctx.stroke()}for(let y=0;y<h;y+=40){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke()}ctx.strokeStyle='rgba(77,168,216,.7)';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(0,persp.horizon);ctx.lineTo(w,persp.horizon);ctx.stroke();ctx.fillStyle='#4da8d8';ctx.font='800 14px system-ui';ctx.fillText('视平线 / eye level',14,persp.horizon-8);
  if($('drawAssist')?.checked!==false){const vps=persp.mode==='one'?[{x:w/2,y:persp.horizon}]:persp.mode==='ortho'?[]:persp.mode==='three'?[persp.vp1,persp.vp2,persp.vp3]:[persp.vp1,persp.vp2];ctx.strokeStyle='rgba(141,123,234,.45)';ctx.lineWidth=1.4;vps.forEach(vp=>{for(let x=-100;x<=w+100;x+=90){ctx.beginPath();ctx.moveTo(x,h);ctx.lineTo(vp.x,vp.y);ctx.stroke()}for(let y=0;y<=h;y+=110){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(vp.x,vp.y);ctx.stroke();ctx.beginPath();ctx.moveTo(w,y);ctx.lineTo(vp.x,vp.y);ctx.stroke()}});ctx.strokeStyle='rgba(142,191,145,.55)';if(persp.mode==='ortho'){for(let x=-200;x<w+300;x+=55){ctx.beginPath();ctx.moveTo(x,h);ctx.lineTo(x+360,0);ctx.stroke()}for(let x=-200;x<w+300;x+=55){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x+360,h);ctx.stroke()}}}
  ctx.lineCap='round';ctx.lineJoin='round';persp.strokes.forEach(s=>{ctx.strokeStyle=s.color;ctx.lineWidth=s.width;ctx.beginPath();s.pts.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.stroke()});if(persp.drawing){ctx.strokeStyle=persp.drawing.color;ctx.lineWidth=persp.drawing.width;ctx.beginPath();persp.drawing.pts.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.stroke();}
  const pts=persp.mode==='one'?[{x:w/2,y:persp.horizon,label:'VP'}]:persp.mode==='ortho'?[]:[{...persp.vp1,label:'VP1'},{...persp.vp2,label:'VP2'}].concat(persp.mode==='three'?[{...persp.vp3,label:'VP3'}]:[]);pts.forEach(p=>{ctx.fillStyle='#ffd166';ctx.strokeStyle='#263240';ctx.lineWidth=2;ctx.beginPath();ctx.arc(p.x,p.y,11,0,TAU);ctx.fill();ctx.stroke();ctx.fillStyle='#263240';ctx.fillText(p.label,p.x+13,p.y-8)});
  ctx.fillStyle='rgba(38,50,64,.78)';ctx.fillText('拖动 VP / 视平线；在网格上画结构线。',18,h-22)}
function bindPerspective(){const c=$('perspectiveCanvas');c.addEventListener('pointerdown',e=>{const p=canvasPoint(c,e);const near=(a,b)=>Math.hypot(p.x-a.x,p.y-a.y)<24;if(persp.mode!=='ortho' && near(persp.vp1)){persp.drag='vp1';return}if(persp.mode!=='one'&&persp.mode!=='ortho'&&near(persp.vp2)){persp.drag='vp2';return}if(persp.mode==='three'&&near(persp.vp3)){persp.drag='vp3';return}if(Math.abs(p.y-persp.horizon)<12){persp.drag='horizon';return}persp.drawing={color:$('pencilColor').value,width:+$('pencilWidth').value,pts:[p]};});c.addEventListener('pointermove',e=>{const p=canvasPoint(c,e);if(persp.drag){if(persp.drag==='horizon'){persp.horizon=p.y;persp.vp1.y=p.y;persp.vp2.y=p.y}else persp[persp.drag]=p;drawPerspective();return}if(persp.drawing){persp.drawing.pts.push(p);drawPerspective();}});window.addEventListener('pointerup',()=>{if(persp.drawing){persp.strokes.push(persp.drawing);persp.drawing=null}persp.drag=null;drawPerspective();});}
function clearPerspectiveDrawing(){persp.strokes=[];drawPerspective();} window.clearPerspectiveDrawing=clearPerspectiveDrawing;
function savePerspectiveSetup(){localStorage.setItem('drawescape_perspective_v6',JSON.stringify({mode:persp.mode,vp1:persp.vp1,vp2:persp.vp2,vp3:persp.vp3,horizon:persp.horizon}));toast('已保存透视坐标系');} window.savePerspectiveSetup=savePerspectiveSetup;

// ---------------- shading ----------------
function renderShadingLab(){const c=$('shadingCanvas'),ctx=c.getContext('2d'),w=c.width,h=c.height;const img=ctx.createImageData(w,h);const base=hexToRgb($('shadeColor')?.value||'#d8a07f');const angle=(+$('shadeAngle')||315)*Math.PI/180;const elev=(+$('shadeHeight')||40)*Math.PI/180;const rough=(+$('shadeRough')||35)/100;const metal=(+$('shadeMetal')||0)/100;const ao=(+$('shadeAO')||40)/100;const L={x:Math.cos(angle)*Math.cos(elev),y:-Math.sin(elev),z:Math.sin(angle)*Math.cos(elev)};const cx=w*.42,cy=h*.5,R=Math.min(w,h)*.34;let term=[];for(let y=0;y<h;y++){for(let x=0;x<w;x++){let dx=(x-cx)/R,dy=(y-cy)/R,d2=dx*dx+dy*dy;let i=(y*w+x)*4;let col={r:255,g:250,b:241};if(d2<=1){let z=Math.sqrt(1-d2),N={x:dx,y:dy,z};let ndl=N.x*L.x+N.y*L.y+N.z*L.z;let diff=Math.max(0,ndl);let fres=Math.pow(1-Math.max(0,z),3);let specPow=lerp(80,8,rough);let H={x:L.x,y:L.y,z:L.z+1};let hl=Math.hypot(H.x,H.y,H.z);H.x/=hl;H.y/=hl;H.z/=hl;let ndh=Math.max(0,N.x*H.x+N.y*H.y+N.z*H.z);let spec=Math.pow(ndh,specPow)*(1-rough*.72);let ambient=.28;let cavity=1-ao*Math.pow(Math.max(0,dy+.55),2)*.8;let env={r:160,g:195,b:210};let diffuse=mix(base,env,metal*.55);col.r=(diffuse.r*(ambient+diff*.82)*cavity)+255*spec*(metal?0.9:.55)+env.r*fres*.28;col.g=(diffuse.g*(ambient+diff*.82)*cavity)+245*spec*(metal?0.9:.55)+env.g*fres*.28;col.b=(diffuse.b*(ambient+diff*.82)*cavity)+220*spec*(metal?0.9:.55)+env.b*fres*.28;if(Math.abs(ndl)<.015)term.push([x,y]);}img.data[i]=clamp(col.r,0,255);img.data[i+1]=clamp(col.g,0,255);img.data[i+2]=clamp(col.b,0,255);img.data[i+3]=255;}}ctx.putImageData(img,0,0);ctx.strokeStyle='#263240';ctx.lineWidth=2;ctx.beginPath();ctx.arc(cx,cy,R,0,TAU);ctx.stroke();if($('showTerminator')?.checked){ctx.fillStyle='#e76f6f';term.filter((_,i)=>i%9===0).forEach(p=>ctx.fillRect(p[0],p[1],2,2));}ctx.fillStyle='#263240';ctx.font='800 14px system-ui';ctx.fillText('红点 = 明暗交界线附近：N · L ≈ 0',18,26);drawMaterialSwatches(ctx,w,h,base,rough,metal);
 $('shadeExplain').innerHTML=`<b>通道拆解</b><br>固有色 Albedo：物体本身的颜色。<br>漫反射 Diffuse：由表面法线与光线夹角决定。<br>高光 Specular：粗糙度越低越小越亮。<br>金属度 Metalness：越高越反射环境，固有色更像反射色。<br>AO：缝隙和贴近处缺少环境光，所以更暗。<br><br><b>绘画练习：</b>先找交界线，再找投影和 AO，最后点高光。不要把所有暗部都画成同一种黑。`;}
function drawMaterialSwatches(ctx,w,h,base,rough,metal){const x=w*.72,y=70;ctx.font='800 13px system-ui';[['Albedo',base],['Light',mix(base,{r:255,g:245,b:180},.55)],['Shadow',mix(base,{r:45,g:55,b:75},.58)],['Env',mix(base,{r:130,g:180,b:205},.35)],['Highlight',mix(base,{r:255,g:255,b:245},1-rough*.5)]].forEach((s,i)=>{ctx.fillStyle=rgbToHex(s[1].r,s[1].g,s[1].b);ctx.fillRect(x,y+i*48,92,32);ctx.strokeStyle='#26324033';ctx.strokeRect(x,y+i*48,92,32);ctx.fillStyle='#263240';ctx.fillText(s[0],x+105,y+i*48+22)});ctx.fillText('Metal '+Math.round(metal*100)+'%',x,y+270)}

// ---------------- folds/nature ----------------
let natureMode='cloth',particles=[];
function setNatureMode(m){natureMode=m;initParticles();renderFoldLab();toast('模式：'+m)} window.setNatureMode=setNatureMode;
function initParticles(){particles=Array.from({length:90},(_,i)=>({x:rand(80,820),y:rand(80,500),vx:rand(-.5,.5),vy:rand(-.6,.3),r:rand(2,8),life:rand(.2,1)}));}
function renderFoldLab(){const c=$('foldCanvas'),ctx=c.getContext('2d'),w=c.width,h=c.height;ctx.clearRect(0,0,w,h);ctx.fillStyle='#fffaf1';ctx.fillRect(0,0,w,h);ctx.strokeStyle='rgba(77,168,216,.18)';for(let x=0;x<w;x+=45){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,h);ctx.stroke()}for(let y=0;y<h;y+=45){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke()}const tension=+$('foldTension').value/100,stiff=+$('foldStiffness').value/100,wind=+$('foldWind').value,complex=+$('foldComplexity').value;
 if(natureMode==='cloth')drawCloth(ctx,w,h,tension,stiff,wind,complex);else if(natureMode==='hair')drawHair(ctx,w,h,tension,stiff,wind,complex);else if(natureMode==='water')drawWater(ctx,w,h,tension,stiff,wind,complex);else drawSmoke(ctx,w,h,tension,stiff,wind,complex);
 const copy={cloth:'固定点越清晰，褶皱越可推理。硬布折线尖锐，软布曲线长而缓。',hair:'头发先看大束，再看分叉；根部固定，末端受重力和风影响。',water:'水没有固定轮廓，画的是绕开障碍物后的流线、波纹、泡沫和反光。',smoke:'烟是密度场：上升、扩散、变淡，被风拉伸，边缘破碎。'}[natureMode];$('foldExplain').innerHTML=`<b>${natureMode}</b><br>${copy}<br><br><b>绘画翻译：</b>看不见的力，通过可见物体的变形出现。先画力场方向，再选择最能表达运动的几条线。`;}
function drawCloth(ctx,w,h,tension,stiff,wind,n){const anchors=[[220,95],[680,95]];ctx.fillStyle='#263240';anchors.forEach(a=>{ctx.beginPath();ctx.arc(a[0],a[1],8,0,TAU);ctx.fill()});ctx.strokeStyle='rgba(38,50,64,.22)';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(anchors[0][0],anchors[0][1]);ctx.lineTo(anchors[1][0],anchors[1][1]);ctx.stroke();for(let i=0;i<n;i++){let t=i/(n-1),x=lerp(220,680,t),len=lerp(330,210,Math.abs(t-.5)*2)*(1-tension*.45),amp=(1-stiff)*42+10;ctx.beginPath();for(let j=0;j<80;j++){let u=j/79,y=95+u*len,x2=x+Math.sin(u*TAU*(1.4+tension*2)+i*.8)*amp*(1-u*.15)+wind*u*1.1;if(j===0)ctx.moveTo(x2,y);else ctx.lineTo(x2,y)}ctx.strokeStyle=i%2?'#6a7f8a':'#263240';ctx.lineWidth=i%2?1.6:2.8;ctx.stroke();}ctx.fillStyle='rgba(255,209,102,.8)';ctx.fillRect(190,86,520,8);ctx.fillStyle='#263240';ctx.font='800 14px system-ui';ctx.fillText('固定点 / anchor',195,75)}
function drawHair(ctx,w,h,tension,stiff,wind,n){ctx.fillStyle='#f2d5b5';ctx.beginPath();ctx.ellipse(450,210,95,120,0,0,TAU);ctx.fill();ctx.strokeStyle='#263240';ctx.lineWidth=2;ctx.stroke();for(let i=0;i<n*2;i++){let a=lerp(Math.PI*.95,Math.PI*2.05,i/(n*2-1));let sx=450+Math.cos(a)*70,sy=150+Math.sin(a)*50;ctx.beginPath();ctx.moveTo(sx,sy);for(let j=1;j<70;j++){let u=j/69;let x=sx+Math.cos(a)*u*80+wind*u*1.4+Math.sin(u*TAU*1.2+i)*18*(1-stiff);let y=sy+u*(190+tension*80)+Math.sin(u*TAU+i)*10;ctx.lineTo(x,y)}ctx.strokeStyle=i%3?'#3a2e2c':'#7b5b54';ctx.lineWidth=lerp(4,1,i/(n*2));ctx.stroke();}ctx.fillStyle='#263240';ctx.fillText('大束 → 分叉，不要一开始画每根头发',230,500)}
function drawWater(ctx,w,h,tension,stiff,wind,n){ctx.fillStyle='#d7eff5';ctx.fillRect(0,0,w,h);ctx.fillStyle='#7f786a';ctx.beginPath();ctx.ellipse(460,300,75,110,0,0,TAU);ctx.fill();ctx.strokeStyle='#263240';ctx.stroke();for(let i=0;i<n*4;i++){let y=80+i*(420/(n*4));ctx.beginPath();for(let x=40;x<860;x+=10){let dx=x-460,dy=y-300;let avoid=9000/(dx*dx+dy*dy+1000);let yy=y+Math.sin(x*.025+i)*8*(1-stiff)+avoid*dy*.28;let xx=x+wind*.22+avoid*dx*.18;if(x===40)ctx.moveTo(xx,yy);else ctx.lineTo(xx,yy)}ctx.strokeStyle=i%4===0?'rgba(38,50,64,.58)':'rgba(77,168,216,.55)';ctx.lineWidth=i%4===0?2.5:1.3;ctx.stroke();}ctx.fillStyle='rgba(255,255,255,.82)';for(let i=0;i<35;i++){ctx.beginPath();ctx.arc(rand(405,535),rand(235,365),rand(1,4),0,TAU);ctx.fill()}ctx.fillStyle='#263240';ctx.fillText('水流绕开石头：前方堆积，两侧加速，后方涡流',215,32)}
function drawSmoke(ctx,w,h,tension,stiff,wind,n){ctx.fillStyle='#f7f1e6';ctx.fillRect(0,0,w,h);for(let i=0;i<particles.length;i++){let p=particles[i];p.x+=wind*.018+(1-stiff)*Math.sin(p.y*.02+i)*.7;p.y-=1.1+tension*1.4;p.r+=.018+(1-stiff)*.03;p.life-=.003;if(p.y<-40||p.life<=0){p.x=rand(360,520);p.y=520;p.r=rand(3,10);p.life=1}let grd=ctx.createRadialGradient(p.x,p.y,0,p.x,p.y,p.r*5);grd.addColorStop(0,`rgba(95,105,120,${.16*p.life})`);grd.addColorStop(1,'rgba(95,105,120,0)');ctx.fillStyle=grd;ctx.beginPath();ctx.arc(p.x,p.y,p.r*5,0,TAU);ctx.fill();}ctx.strokeStyle='rgba(38,50,64,.35)';ctx.lineWidth=2;for(let i=0;i<n;i++){ctx.beginPath();for(let j=0;j<80;j++){let u=j/79;let x=450+wind*u*2+Math.sin(u*TAU*1.6+i)*60*u*(1-stiff);let y=520-u*440;if(j===0)ctx.moveTo(x,y);else ctx.lineTo(x,y)}ctx.stroke();}ctx.fillStyle='#263240';ctx.fillText('烟不是轮廓，是密度场：上升、扩散、破碎、变淡',220,32)}
function animateNature(){if(natureMode==='smoke'){renderFoldLab()}requestAnimationFrame(animateNature)}

// ---------------- face ----------------
function renderFaceLab(){const c=$('faceCanvas'),ctx=c.getContext('2d'),w=c.width,h=c.height;ctx.clearRect(0,0,w,h);ctx.fillStyle='#fffaf1';ctx.fillRect(0,0,w,h);const yaw=+$('faceYaw').value/55,pitch=+$('facePitch').value/30,anime=+$('animeLevel').value/100,chibi=+$('chibiLevel').value/100,line=+$('faceLine').value;const cx=w/2,cy=h/2+chibi*20;const headH=lerp(300,235,chibi),headW=lerp(205,185,chibi);ctx.lineCap='round';ctx.lineJoin='round';ctx.strokeStyle='#263240';ctx.lineWidth=line;ctx.fillStyle='#f2d5bd';ctx.beginPath();ctx.ellipse(cx,cy,headW/2,headH/2,0,0,TAU);ctx.fill();ctx.stroke();const centerShift=yaw*headW*.28;const eyeY=cy-headH*.11+pitch*25,noseY=cy+headH*.10+pitch*16,mouthY=cy+headH*.25+pitch*10;ctx.strokeStyle='rgba(77,168,216,.8)';ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(cx+centerShift,cy,headW*.18,headH*.5,0,Math.PI*.5,Math.PI*1.5,yaw>0);ctx.stroke();ctx.beginPath();ctx.moveTo(cx-headW*.45,eyeY);ctx.quadraticCurveTo(cx,eyeY+pitch*12,cx+headW*.45,eyeY);ctx.stroke();ctx.beginPath();ctx.moveTo(cx-headW*.4,noseY);ctx.quadraticCurveTo(cx,noseY+pitch*8,cx+headW*.4,noseY);ctx.stroke();ctx.beginPath();ctx.moveTo(cx-headW*.35,mouthY);ctx.quadraticCurveTo(cx,mouthY+pitch*6,cx+headW*.35,mouthY);ctx.stroke();
 if($('facePlanes').checked){ctx.fillStyle='rgba(255,209,102,.22)';ctx.beginPath();ctx.moveTo(cx+centerShift,cy-headH*.45);ctx.lineTo(cx+headW*.45,eyeY);ctx.lineTo(cx+headW*.30,cy+headH*.35);ctx.lineTo(cx+centerShift,cy+headH*.48);ctx.closePath();ctx.fill();ctx.fillStyle='rgba(141,123,234,.18)';ctx.beginPath();ctx.moveTo(cx+centerShift,cy-headH*.45);ctx.lineTo(cx-headW*.45,eyeY);ctx.lineTo(cx-headW*.30,cy+headH*.35);ctx.lineTo(cx+centerShift,cy+headH*.48);ctx.closePath();ctx.fill();}
 const eyeSize=lerp(18,40,anime)*(1+chibi*.45),eyeGap=headW*.18;ctx.fillStyle='#263240';[-1,1].forEach(side=>{let ex=cx+centerShift*.45+side*(eyeGap+headW*.1*(1-Math.abs(yaw)*.4));let ew=eyeSize*(side*yaw>0?0.78:1.05);ctx.beginPath();ctx.ellipse(ex,eyeY+8,ew,eyeSize*.55,0,0,TAU);ctx.fill();ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(ex-ew*.25,eyeY,eyeSize*.17,0,TAU);ctx.fill();ctx.fillStyle='#263240';});ctx.strokeStyle='#6d4e48';ctx.lineWidth=line;ctx.beginPath();ctx.moveTo(cx+centerShift,noseY-38);ctx.quadraticCurveTo(cx+centerShift+28*yaw,noseY,cx+centerShift-8,noseY+18);ctx.stroke();ctx.beginPath();ctx.moveTo(cx-42,mouthY+10);ctx.quadraticCurveTo(cx,mouthY+25+chibi*8,cx+42,mouthY+10);ctx.stroke();
 const la=(+$('faceLight').value)*Math.PI/180;ctx.strokeStyle='rgba(231,111,111,.55)';ctx.lineWidth=3;ctx.beginPath();ctx.arc(cx,cy,headW*.58,la+Math.PI*.5,la+Math.PI*1.05);ctx.stroke();ctx.fillStyle='#263240';ctx.font='800 14px system-ui';ctx.fillText('这是结构代理模型：用来校准中心线、五官锚点、面块和光向。',34,32);$('faceExplain').innerHTML=`<b>为什么以前会画错：</b><br>不参考对象时，脑中的头部模型容易缺少三件事：中心线随转头移动、五官锚点随面块转动、光影随法线变化。<br><br><b>动漫/Q版：</b>不是乱改比例，而是提高眼睛信息权重、降低鼻口细节、放大头部情绪表达，同时仍保持中心线和透视关系。`;}

// ---------------- init ----------------
function init(){renderPipeline();renderSources();renderMap();cover();bindFallbackDrag();bindPerspective();refreshSavedViews();if(!world.objects.length){addWorldShape('box');addWorldShape('sphere');world.objects[1].x=.9;world.objects[1].y=.25;world.selected=world.objects[0].id;updateSelect();}drawPerspective();renderShadingLab();initParticles();renderFoldLab();animateNature();renderFaceLab();}
document.addEventListener('DOMContentLoaded',init);
