/*
Drawescape｜绘梦境 V4
修复重点：不再让 Three.js CDN 失败阻塞整页；默认 Canvas 2.5D 可拖动引擎可本地运行。
*/
'use strict';
const $=(s,r=document)=>r.querySelector(s);
const $$=(s,r=document)=>Array.from(r.querySelectorAll(s));
const TAU=Math.PI*2;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const lerp=(a,b,t)=>a+(b-a)*t;
const storeKey='drawescape-v4-state';
const state=Object.assign({page:'home',theme:'paper',geo:false,focus:false,lowMotion:false,completed:{}}, JSON.parse(localStorage.getItem(storeKey)||'{}'));
function persist(){localStorage.setItem(storeKey,JSON.stringify(state));}
function toast(msg){const t=$('#toast');t.textContent=msg;t.hidden=false;clearTimeout(toast._timer);toast._timer=setTimeout(()=>t.hidden=true,2200);}
function resizeCanvas(c){const r=c.getBoundingClientRect();const d=Math.min(window.devicePixelRatio||1,2);c.width=Math.max(1,Math.floor(r.width*d));c.height=Math.max(1,Math.floor(r.height*d));const ctx=c.getContext('2d');ctx.setTransform(d,0,0,d,0,0);return {w:r.width,h:r.height,ctx};}
function hexToRgb(hex){hex=hex.replace('#','');return {r:parseInt(hex.slice(0,2),16),g:parseInt(hex.slice(2,4),16),b:parseInt(hex.slice(4,6),16)};}
function rgbToHex(r,g,b){return '#'+[r,g,b].map(v=>clamp(Math.round(v),0,255).toString(16).padStart(2,'0')).join('');}
function rgbToHsl(r,g,b){r/=255;g/=255;b/=255;const max=Math.max(r,g,b),min=Math.min(r,g,b);let h=0,s=0,l=(max+min)/2;if(max!==min){const d=max-min;s=l>0.5?d/(2-max-min):d/(max+min);switch(max){case r:h=(g-b)/d+(g<b?6:0);break;case g:h=(b-r)/d+2;break;case b:h=(r-g)/d+4;break;}h*=60;}return {h,s:s*100,l:l*100};}
function hslToRgb(h,s,l){h=((h%360)+360)%360;s/=100;l/=100;const c=(1-Math.abs(2*l-1))*s;const x=c*(1-Math.abs((h/60)%2-1));const m=l-c/2;let r=0,g=0,b=0;if(h<60){r=c;g=x;}else if(h<120){r=x;g=c;}else if(h<180){g=c;b=x;}else if(h<240){g=x;b=c;}else if(h<300){r=x;b=c;}else{r=c;b=x;}return {r:(r+m)*255,g:(g+m)*255,b:(b+m)*255};}
function hslHex(h,s,l){const c=hslToRgb(h,s,l);return rgbToHex(c.r,c.g,c.b);} 

const zones=[
 {id:'line',name:'线之海',en:'Line Sea',icon:'〰️',color:'#55bfd5',tool:'拓扑线笔',core:'线不是边框，而是深度、法线、材质或结构发生变化的证据。',lab:'给形体添加结构线和轮廓线。',page:'studio'},
 {id:'prop',name:'比例森林',en:'Proportion Forest',icon:'🌲',color:'#8db596',tool:'比例罗盘',core:'比例不是死背，是锚点、单位长度和相互关系。',lab:'短时记忆一个形体，再用锚点复原。',page:'levels'},
 {id:'cam',name:'相机塔',en:'Camera Tower',icon:'📷',color:'#ffd166',tool:'透视眼镜',core:'透视是相机投影。视平线、FOV、消失点都可以被调整。',lab:'拖动消失点，修复盒子透视。',page:'perspective'},
 {id:'depth',name:'深度湖',en:'Depth Lake',icon:'💧',color:'#9287e8',tool:'深度灯笼',core:'深度图只记录远近，不等于阴影。先判断近中远，再画光影。',lab:'把画面分成近景、中景、远景。',page:'perspective'},
 {id:'light',name:'光之月台',en:'Light Station',icon:'🌙',color:'#ffd166',tool:'法线罗盘',core:'明暗来自表面朝向与光线的关系。高光和阴影都有几何位置。',lab:'调光源角度，观察体块明暗变化。',page:'studio'},
 {id:'mat',name:'材质星市',en:'Material Bazaar',icon:'🔮',color:'#f29ba7',tool:'材质晶球',core:'质感来自粗糙度、反射、透光、纹理和边缘反光。',lab:'调粗糙度和金属度，比较高光变化。',page:'studio'},
 {id:'wind',name:'风的剧场',en:'Wind Theater',icon:'🍃',color:'#b7d6ee',tool:'风向羽毛',core:'风不可见，要画它经过头发、布料、树叶和烟时留下的证据。',lab:'拖动力场点，看飘带和线条节奏。',page:'flow'},
 {id:'fluid',name:'流体之谷',en:'Fluid Valley',icon:'🌊',color:'#47b7db',tool:'流线笔',core:'水、烟、云、火是密度、速度、边缘和涡流的组合。',lab:'水绕石头，烟向上扩散，雨受风偏转。',page:'flow'},
 {id:'fold',name:'折叠云城',en:'Folding City',icon:'🏙️',color:'#b692f6',tool:'世界折叠器',core:'风格化是信息压缩：保留什么、舍弃什么、夸张什么。',lab:'把复杂画面压缩成 5 条线 / 3 个明暗块。',page:'color'}
];
const zoneMap=Object.fromEntries(zones.map(z=>[z.id,z]));
const quests=[
 {id:'anchor',icon:'📍',title:'锚点记忆',task:'看 3 秒几何组合，然后用点和线复原主要比例。',page:'studio',reward:8},
 {id:'vp',icon:'📐',title:'消失点修复',task:'拖动消失点，让盒子的边线重新汇聚。',page:'perspective',reward:10},
 {id:'depth',icon:'💧',title:'深度排序',task:'只判断近中远，不画阴影。把场景分层。',page:'perspective',reward:7},
 {id:'light',icon:'🌙',title:'光源侦探',task:'通过明暗猜光从哪里来，再调光源验证。',page:'studio',reward:9},
 {id:'material',icon:'🔮',title:'材质晶球',task:'通过高光大小判断粗糙度和材质。',page:'studio',reward:9},
 {id:'flow',icon:'🍃',title:'不可见的风',task:'用飘带、水线和烟雾证明风的方向。',page:'flow',reward:10},
 {id:'palette',icon:'🎨',title:'调色折叠',task:'用一个主色生成亮部、暗部、反光和氛围色。',page:'color',reward:8},
 {id:'compress',icon:'✦',title:'五线压缩',task:'把复杂场景压缩成 5 条最重要的结构线。',page:'perspective',reward:12}
];
const sources=[
 {tag:'CG',title:'透视投影 / Camera Projection',text:'画面中的近大远小可以理解为三维点经过相机投影到二维平面。对应相机 FOV、视平线和消失点。'},
 {tag:'CV',title:'单目深度 / Depth Cues',text:'遮挡、相对大小、纹理密度、空气透视和位置高低，都是单张图像中的深度线索。'},
 {tag:'CG',title:'法线与光照 / Normal · Lighting',text:'漫反射强弱取决于表面朝向与光线方向。画明暗前先判断每个面朝哪里。'},
 {tag:'Material',title:'粗糙度与高光 / Roughness',text:'光滑表面高光小而亮；粗糙表面高光大而散。绘画质感可以从高光形状开始推理。'},
 {tag:'Modeling',title:'线稿到模型 / Sketch to Model',text:'轮廓可以推拉，侧影可以旋转，路径可以扫掠，深度层可以转成曲面。这是从绘画进入 Rhino/SU/Blender 的桥。'},
 {tag:'Flow',title:'风水流体 / Flow Lines',text:'风、水、烟并没有稳定边界，绘画时更适合画力场、流线、密度变化和边缘破碎。'},
 {tag:'Color',title:'调色通道 / Color Channels',text:'最终颜色由固有色、光照色、环境反光、高光、大气深度和情绪氛围共同压缩而成。'},
 {tag:'ND',title:'小关卡学习 / Low-load Learning',text:'每次只训练一个微技能：比例、深度、透视、光源或材质。清晰反馈比模糊评价更安全。'}
];

function showPage(id){state.page=id;persist();$$('.page').forEach(p=>p.classList.toggle('active',p.id===id));$$('[data-goto]').forEach(b=>b.classList.toggle('active',b.dataset.goto===id));if(id==='studio')modelLab.ensure();if(id==='perspective')perspPad.ensure();if(id==='color')colorLab.ensure();if(id==='flow')flowLab.ensure();}
function initNav(){ $$('[data-goto]').forEach(b=>b.addEventListener('click',()=>showPage(b.dataset.goto))); $('#sleepBtn').onclick=()=>{document.body.classList.toggle('theme-night');state.theme=document.body.classList.contains('theme-night')?'night':'paper';persist();}; $('#geoBtn').onclick=()=>{document.body.classList.toggle('theme-geo');state.geo=document.body.classList.contains('theme-geo');persist();}; $('#focusBtn').onclick=()=>{document.body.classList.toggle('focus');state.focus=document.body.classList.contains('focus');persist();}; $('#motionBtn').onclick=()=>{document.body.classList.toggle('low-motion');state.lowMotion=document.body.classList.contains('low-motion');persist();}; document.body.classList.toggle('theme-night',state.theme==='night');document.body.classList.toggle('theme-geo',!!state.geo);document.body.classList.toggle('focus',!!state.focus);document.body.classList.toggle('low-motion',!!state.lowMotion);}

const sky={start(){const c=$('#sky'),ctx=c.getContext('2d');let pts=[];const resize=()=>{const r=resizeCanvas(c);pts=Array.from({length:90},()=>({x:Math.random()*r.w,y:Math.random()*r.h,r:Math.random()*1.8+.4,a:Math.random()*TAU,s:Math.random()*0.02+.006}));};window.addEventListener('resize',resize);resize();function loop(){const {w,h}=c.getBoundingClientRect();if(!document.body.classList.contains('low-motion')){ctx.clearRect(0,0,w,h);pts.forEach(p=>{p.a+=p.s;ctx.globalAlpha=.22+.22*Math.sin(p.a);ctx.fillStyle='#55bfd5';ctx.beginPath();ctx.arc(p.x,p.y,p.r,0,TAU);ctx.fill();});}requestAnimationFrame(loop);}loop();}};
const portal={start(){const c=$('#portalCanvas'),ctx=c.getContext('2d');let t=0,w=1,h=1;function resize(){const r=resizeCanvas(c);w=r.w;h=r.h;}window.addEventListener('resize',resize);resize();function project(x,y,z){const f=520/(520+z);return {x:w/2+x*f,y:h/2+y*f,s:f};}function loop(){t+=0.012;ctx.clearRect(0,0,w,h);drawPortalGrid(ctx,w,h,t);const shapes=[[-180,-20,0,70,'#ffd166'],[-70,46,80,58,'#f29ba7'],[80,-28,-40,64,'#9287e8'],[188,38,120,52,'#55bfd5']];shapes.forEach((s,i)=>{const p=project(s[0]+Math.sin(t+i)*18,s[1]+Math.cos(t*.8+i)*16,s[2]+Math.sin(t+i)*60);ctx.save();ctx.translate(p.x,p.y);ctx.scale(p.s,p.s);ctx.rotate(t*(i%2?-.4:.35));ctx.globalAlpha=.75;ctx.fillStyle=s[4];ctx.strokeStyle='rgba(255,255,255,.9)';ctx.lineWidth=2;if(i===0){roundRect(ctx,-s[3]/2,-s[3]/2,s[3],s[3],16);ctx.fill();ctx.stroke();}else if(i===1){ctx.beginPath();ctx.arc(0,0,s[3]/2,0,TAU);ctx.fill();ctx.stroke();}else if(i===2){ctx.beginPath();ctx.moveTo(0,-s[3]/2);ctx.lineTo(s[3]/2,s[3]/2);ctx.lineTo(-s[3]/2,s[3]/2);ctx.closePath();ctx.fill();ctx.stroke();}else{ctx.beginPath();ctx.ellipse(0,0,s[3]*.65,s[3]*.34,0,0,TAU);ctx.fill();ctx.stroke();}ctx.restore();});ctx.save();ctx.strokeStyle='rgba(255,255,255,.65)';for(let i=0;i<3;i++){const y=h*((t*.075+i*.37)%1);ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke();}ctx.restore();requestAnimationFrame(loop);}loop();}};
function drawPortalGrid(ctx,w,h,t){ctx.save();ctx.globalAlpha=.42;ctx.strokeStyle='#55bfd5';ctx.lineWidth=1;const vp={x:w*.5+Math.sin(t)*64,y:h*.42};for(let x=-80;x<w+80;x+=42){ctx.beginPath();ctx.moveTo(x,h);ctx.lineTo(vp.x,vp.y);ctx.stroke();}for(let i=0;i<14;i++){const y=h*.48+i*i*3.2;ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke();}ctx.restore();}
function roundRect(ctx,x,y,w,h,r){ctx.beginPath();ctx.moveTo(x+r,y);ctx.arcTo(x+w,y,x+w,y+h,r);ctx.arcTo(x+w,y+h,x,y+h,r);ctx.arcTo(x,y+h,x,y,r);ctx.arcTo(x,y,x+w,y,r);ctx.closePath();}

function renderMap(){const svg=$('#worldMap');const coords={line:[130,135],prop:[290,270],cam:[440,145],depth:[585,292],light:[735,150],mat:[890,292],wind:[450,500],fluid:[650,520],fold:[940,470]};const links=[['line','prop'],['line','cam'],['prop','depth'],['cam','depth'],['depth','light'],['light','mat'],['mat','wind'],['wind','fluid'],['fluid','fold'],['mat','fold'],['cam','fold']];svg.innerHTML='<defs><filter id="glow"><feGaussianBlur stdDeviation="3" result="b"/><feMerge><feMergeNode in="b"/><feMergeNode in="SourceGraphic"/></feMerge></filter></defs>'+links.map(([a,b])=>{const A=coords[a],B=coords[b];return `<path class="map-edge" d="M${A[0]},${A[1]} C${(A[0]+B[0])/2},${A[1]} ${(A[0]+B[0])/2},${B[1]} ${B[0]},${B[1]}"/>`;}).join('')+zones.map(z=>{const p=coords[z.id];return `<g class="map-node" data-zone="${z.id}" transform="translate(${p[0]},${p[1]})"><circle r="58" fill="${z.color}" filter="url(#glow)"></circle><text text-anchor="middle" y="-6" font-size="22">${z.icon}</text><text text-anchor="middle" y="26">${z.name}</text></g>`;}).join('');$$('.map-node',svg).forEach(n=>n.addEventListener('click',()=>showZone(n.dataset.zone)));showZone('cam');}
function showZone(id){const z=zoneMap[id];$('#zonePanel').innerHTML=`<h3>${z.icon} ${z.name}<br><small>${z.en}</small></h3><p><b>核心：</b>${z.core}</p><p><b>获得道具：</b>${z.tool}</p><p><b>互动关卡：</b>${z.lab}</p><button class="primary wide" data-goto="${z.page}">进入对应实验</button><div><span class="tag">几何</span><span class="tag">推理</span><span class="tag">可视化</span></div>`;$('#zonePanel [data-goto]').onclick=e=>showPage(e.currentTarget.dataset.goto);}
function renderQuests(){const g=$('#questGrid');g.innerHTML=quests.map(q=>`<article class="quest-card card"><h3>${q.icon} ${q.title}</h3><p>${q.task}</p><p>奖励：${q.reward} 星尘 · 状态：${state.completed[q.id]?'完成':'未完成'}</p><button data-q="${q.id}" data-page="${q.page}">${state.completed[q.id]?'再玩一次':'开始关卡'}</button></article>`).join('');$$('[data-q]',g).forEach(b=>b.onclick=()=>{showPage(b.dataset.page);state.completed[b.dataset.q]=true;persist();toast('关卡已启动：'+b.closest('article').querySelector('h3').textContent);renderQuests();});}
function renderSources(){$('#sourceGrid').innerHTML=sources.map(s=>`<article class="source-card card"><span class="source-tag">${s.tag}</span><h3>${s.title}</h3><p>${s.text}</p></article>`).join('');}

class ModelLab{
  constructor(){this.inited=false;this.objects=[];this.selected=null;this.drag=null;this.cam={yaw:24,pitch:16,fov:520,panX:0,panY:20};this.light=35;this.rough=42;}
  ensure(){if(this.inited){this.resize();return;}this.inited=true;this.c=$('#modelCanvas');this.ctx=this.c.getContext('2d');this.bind();this.loadScene('still');this.resize();this.loop();}
  bind(){window.addEventListener('resize',()=>this.resize());this.c.addEventListener('pointerdown',e=>this.down(e));this.c.addEventListener('pointermove',e=>this.move(e));window.addEventListener('pointerup',()=>this.up());this.c.addEventListener('wheel',e=>{e.preventDefault();this.cam.fov=clamp(this.cam.fov-e.deltaY*.5,260,900);$('#fov').value=this.cam.fov;}, {passive:false});$$('[data-shape]').forEach(b=>b.onclick=()=>this.add(b.dataset.shape));$('#sceneStill').onclick=()=>this.loadScene('still');$('#sceneStreet').onclick=()=>this.loadScene('street');$('#sceneRoom').onclick=()=>this.loadScene('room');$('#clearScene').onclick=()=>{this.objects=[];};['yaw','pitch','fov','lightAngle','roughness'].forEach(id=>{$('#'+id).oninput=e=>{if(id==='yaw')this.cam.yaw=+e.target.value;if(id==='pitch')this.cam.pitch=+e.target.value;if(id==='fov')this.cam.fov=+e.target.value;if(id==='lightAngle')this.light=+e.target.value;if(id==='roughness')this.rough=+e.target.value;};});$$('[data-bridge]').forEach(b=>b.onclick=()=>this.bridge(b.dataset.bridge));$('#tryThree').onclick=()=>this.tryThree();}
  resize(){const r=resizeCanvas(this.c);this.w=r.w;this.h=r.h;}
  add(type){const base={type,x:0,y:0,z:0,w:1.1,h:1.1,d:1.1,color:['#ffd166','#f29ba7','#55bfd5','#9287e8','#8db596'][this.objects.length%5]};if(type==='sphere')Object.assign(base,{w:1.25,h:1.25,d:1.25});if(type==='cylinder')Object.assign(base,{w:1,h:1.5,d:1});if(type==='cone')Object.assign(base,{w:1.2,h:1.55,d:1.2});if(type==='ribbon')Object.assign(base,{w:2.4,h:.42,d:.9});if(type==='room')Object.assign(base,{w:4,h:2.6,d:3.8,color:'#b7d6ee'});base.x=(Math.random()-.5)*3;base.z=(Math.random()-.5)*2;this.objects.push(base);this.selected=base;}
  loadScene(kind){this.objects=[];if(kind==='still'){this.objects.push({type:'cube',x:-1.2,y:0,z:.2,w:1.4,h:1.4,d:1.4,color:'#ffd166'},{type:'sphere',x:.65,y:.05,z:-.3,w:1.3,h:1.3,d:1.3,color:'#f29ba7'},{type:'cylinder',x:1.8,y:.05,z:.45,w:.85,h:1.8,d:.85,color:'#55bfd5'});}if(kind==='street'){for(let i=0;i<8;i++){this.objects.push({type:'cube',x:(i%2?2.4:-2.4),y:0,z:-i*1.45,w:1.2+Math.random()*.5,h:1.6+Math.random()*1.7,d:1,color:i%2?'#9287e8':'#55bfd5'});}this.cam.yaw=0;this.cam.pitch=10;this.cam.fov=440;}if(kind==='room'){this.objects.push({type:'room',x:0,y:0,z:-1,w:5,h:3,d:5,color:'#dfeefa'},{type:'cube',x:-1.25,y:0,z:-.4,w:1.6,h:.8,d:1.4,color:'#ffd166'},{type:'cylinder',x:1.4,y:0,z:.4,w:.65,h:1.5,d:.65,color:'#f29ba7'});this.cam.yaw=18;this.cam.pitch=8;this.cam.fov=500;}['yaw','pitch','fov'].forEach(id=>{$('#'+id).value=this.cam[id]});}
  rot(p){const yaw=this.cam.yaw*Math.PI/180,pitch=this.cam.pitch*Math.PI/180;let x=p.x,z=p.z;const cy=Math.cos(yaw),sy=Math.sin(yaw);let x1=x*cy-z*sy,z1=x*sy+z*cy;let y=p.y;const cp=Math.cos(pitch),sp=Math.sin(pitch);let y1=y*cp-z1*sp,z2=y*sp+z1*cp;return {x:x1,y:y1,z:z2};}
  proj(p){const r=this.rot(p);const depth=this.cam.fov/(this.cam.fov+(r.z+6)*70);return {x:this.w/2+this.cam.panX+r.x*140*depth,y:this.h/2+this.cam.panY-r.y*140*depth,s:depth,z:r.z};}
  corners(o){const X=o.w/2,Y=o.h/2,Z=o.d/2;return [{x:o.x-X,y:o.y-Y,z:o.z-Z},{x:o.x+X,y:o.y-Y,z:o.z-Z},{x:o.x+X,y:o.y+Y,z:o.z-Z},{x:o.x-X,y:o.y+Y,z:o.z-Z},{x:o.x-X,y:o.y-Y,z:o.z+Z},{x:o.x+X,y:o.y-Y,z:o.z+Z},{x:o.x+X,y:o.y+Y,z:o.z+Z},{x:o.x-X,y:o.y+Y,z:o.z+Z}];}
  drawGrid(){const ctx=this.ctx;ctx.save();ctx.strokeStyle='rgba(85,191,213,.28)';ctx.lineWidth=1;for(let i=-10;i<=10;i++){this.line3({x:i,y:-.72,z:-10},{x:i,y:-.72,z:8});this.line3({x:-10,y:-.72,z:i},{x:10,y:-.72,z:i});}ctx.restore();}
  line3(a,b){const A=this.proj(a),B=this.proj(b);this.ctx.beginPath();this.ctx.moveTo(A.x,A.y);this.ctx.lineTo(B.x,B.y);this.ctx.stroke();}
  drawObject(o){if(o.type==='sphere')return this.drawSphere(o);if(o.type==='cylinder')return this.drawCylinder(o);if(o.type==='cone')return this.drawCone(o);if(o.type==='ribbon')return this.drawRibbon(o);return this.drawCube(o);}
  drawCube(o){const ctx=this.ctx;const cs=this.corners(o).map(p=>this.proj(p));const faces=[[0,1,2,3],[1,5,6,2],[4,5,6,7],[0,4,7,3],[3,2,6,7],[0,1,5,4]];const light=(this.light*Math.PI/180);faces.map(f=>({f,z:f.reduce((s,i)=>s+cs[i].z,0)/4})).sort((a,b)=>a.z-b.z).forEach((it,idx)=>{ctx.beginPath();it.f.forEach((i,j)=>j?ctx.lineTo(cs[i].x,cs[i].y):ctx.moveTo(cs[i].x,cs[i].y));ctx.closePath();ctx.fillStyle=this.shade(o.color,.75+idx*.04);ctx.fill();ctx.strokeStyle=o===this.selected?'#ffd166':'rgba(36,49,58,.42)';ctx.lineWidth=o===this.selected?3:1.4;if($('#wire').checked)ctx.stroke();});if($('#projection').checked){ctx.save();ctx.strokeStyle='rgba(85,191,213,.32)';ctx.setLineDash([6,6]);[0,1,2,3].forEach(i=>{ctx.beginPath();ctx.moveTo(cs[i].x,cs[i].y);ctx.lineTo(this.w/2,this.h*.42);ctx.stroke();});ctx.restore();}}
  drawSphere(o){const ctx=this.ctx,p=this.proj({x:o.x,y:o.y,z:o.z});const r=o.w*70*p.s;const g=ctx.createRadialGradient(p.x-r*.35,p.y-r*.42,r*.08,p.x,p.y,r);g.addColorStop(0,'#fff');g.addColorStop(.18,this.shade(o.color,1.15));g.addColorStop(1,this.shade(o.color,.48+this.rough/240));ctx.fillStyle=g;ctx.beginPath();ctx.arc(p.x,p.y,r,0,TAU);ctx.fill();ctx.strokeStyle=o===this.selected?'#ffd166':'rgba(36,49,58,.42)';ctx.lineWidth=o===this.selected?3:1.2;ctx.stroke();if($('#wire').checked){ctx.strokeStyle='rgba(36,49,58,.25)';for(let i=-2;i<=2;i++){ctx.beginPath();ctx.ellipse(p.x,p.y,r,Math.abs(r*(.18+i*.15)),0,0,TAU);ctx.stroke();}}}
  drawCylinder(o){const ctx=this.ctx,top=this.proj({x:o.x,y:o.y+o.h/2,z:o.z}),bot=this.proj({x:o.x,y:o.y-o.h/2,z:o.z});const rx=o.w*58*top.s,ry=rx*.28;ctx.fillStyle=this.shade(o.color,.74);ctx.beginPath();ctx.ellipse(bot.x,bot.y,rx,ry,0,0,TAU);ctx.fill();ctx.beginPath();ctx.moveTo(top.x-rx,top.y);ctx.lineTo(bot.x-rx,bot.y);ctx.ellipse(bot.x,bot.y,rx,ry,Math.PI,Math.PI,0,true);ctx.lineTo(top.x+rx,top.y);ctx.ellipse(top.x,top.y,rx,ry,0,0,Math.PI,true);ctx.fillStyle=this.shade(o.color,.88);ctx.fill();ctx.strokeStyle=o===this.selected?'#ffd166':'rgba(36,49,58,.42)';ctx.lineWidth=o===this.selected?3:1.2;ctx.stroke();ctx.beginPath();ctx.ellipse(top.x,top.y,rx,ry,0,0,TAU);ctx.fillStyle=this.shade(o.color,1.08);ctx.fill();ctx.stroke();}
  drawCone(o){const ctx=this.ctx,top=this.proj({x:o.x,y:o.y+o.h/2,z:o.z}),bot=this.proj({x:o.x,y:o.y-o.h/2,z:o.z});const rx=o.w*62*bot.s,ry=rx*.28;ctx.beginPath();ctx.moveTo(top.x,top.y);ctx.lineTo(bot.x+rx,bot.y);ctx.ellipse(bot.x,bot.y,rx,ry,0,0,Math.PI);ctx.lineTo(top.x,top.y);ctx.closePath();ctx.fillStyle=this.shade(o.color,.88);ctx.fill();ctx.strokeStyle=o===this.selected?'#ffd166':'rgba(36,49,58,.42)';ctx.lineWidth=o===this.selected?3:1.2;ctx.stroke();}
  drawRibbon(o){const ctx=this.ctx;ctx.save();ctx.strokeStyle=o.color;ctx.lineWidth=18;ctx.lineCap='round';ctx.globalAlpha=.72;ctx.beginPath();for(let i=0;i<18;i++){const x=o.x-1.2+i*.14,y=o.y+.18*Math.sin(i*.8+performance.now()/800),z=o.z+.35*Math.cos(i*.48);const p=this.proj({x,y,z});i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y);}ctx.stroke();ctx.lineWidth=1.5;ctx.strokeStyle='rgba(36,49,58,.35)';ctx.stroke();ctx.restore();}
  shade(hex,k){const c=hexToRgb(hex);return rgbToHex(c.r*k,c.g*k,c.b*k);}
  pick(x,y){let best=null,bd=1e9;for(const o of this.objects){const p=this.proj({x:o.x,y:o.y,z:o.z});const d=(p.x-x)**2+(p.y-y)**2;if(d<bd){bd=d;best=o;}}return bd<12000?best:null;}
  down(e){const r=this.c.getBoundingClientRect();const x=e.clientX-r.left,y=e.clientY-r.top;if(e.shiftKey){this.drag={mode:'pan',x,y,panX:this.cam.panX,panY:this.cam.panY};return;}const o=this.pick(x,y);this.selected=o;if(o){const p=this.proj({x:o.x,y:o.y,z:o.z});this.drag={mode:'obj',o,dx:x-p.x,dy:y-p.y};}}
  move(e){if(!this.drag)return;const r=this.c.getBoundingClientRect();const x=e.clientX-r.left,y=e.clientY-r.top;if(this.drag.mode==='pan'){this.cam.panX=this.drag.panX+x-this.drag.x;this.cam.panY=this.drag.panY+y-this.drag.y;return;}const o=this.drag.o;const scale=1/(140*(this.proj({x:o.x,y:o.y,z:o.z}).s||1));o.x+=(x-this.drag.dx-this.proj({x:o.x,y:o.y,z:o.z}).x)*scale*.9;o.y-=(y-this.drag.dy-this.proj({x:o.x,y:o.y,z:o.z}).y)*scale*.9;}
  up(){this.drag=null;}
  bridge(type){const text={extrude:'轮廓 → 推拉：闭合线稿可以变成有厚度的盒体、建筑、桌面。',lathe:'侧影 → 旋转体：杯子、瓶子、柱子可以由一条侧影绕轴旋转生成。',sweep:'路径 → 扫掠：头发、管线、飘带、水流可以沿中心线扫出体积。',surface:'深度 → 曲面：深度层像一张高度场，可以变成地形、布面、脸部体积。'}[type];$('#studioPrinciple').textContent=text;toast(text);}
  async tryThree(){const el=$('#engineStatus');el.textContent='Engine: 正在尝试加载 Three.js...';try{const THREE=await import('https://cdn.jsdelivr.net/npm/three@0.166.1/build/three.module.js');el.textContent='Engine: Three.js 可加载。V4 保留 Canvas 主引擎，下一版可切换真实 WebGL 场景。';toast('Three.js 加载成功：可以继续升级真实 WebGL。');console.log('THREE loaded',THREE.REVISION);}catch(err){el.textContent='Engine: CDN 加载失败，已自动保持 Canvas 2.5D，不影响使用。';toast('Three.js 没加载成功，但页面不会再坏。');}}
  loop(){const ctx=this.ctx;if(!ctx)return;ctx.clearRect(0,0,this.w,this.h);const bg=ctx.createLinearGradient(0,0,0,this.h);bg.addColorStop(0,document.body.classList.contains('theme-night')?'#101827':'#eefbff');bg.addColorStop(1,document.body.classList.contains('theme-night')?'#151f32':'#fff7ec');ctx.fillStyle=bg;ctx.fillRect(0,0,this.w,this.h);this.drawGrid();this.objects.slice().sort((a,b)=>this.rot({x:a.x,y:a.y,z:a.z}).z-this.rot({x:b.x,y:b.y,z:b.z}).z).forEach(o=>this.drawObject(o));requestAnimationFrame(()=>this.loop());}
}
const modelLab=new ModelLab();

class PerspectivePad{
 constructor(){this.inited=false;this.mode='2p';this.tool='draw';this.strokes=[];this.current=null;this.dragVp=null;this.vps={left:{x:120,y:270,c:'#55bfd5'},right:{x:800,y:280,c:'#9287e8'},top:{x:470,y:70,c:'#ffd166'}};this.horizon=290;this.ref=null;}
 ensure(){if(this.inited){this.resize();return;}this.inited=true;this.c=$('#perspCanvas');this.ctx=this.c.getContext('2d');this.bind();this.resize();this.draw();}
 bind(){window.addEventListener('resize',()=>this.resize());this.c.addEventListener('pointerdown',e=>this.down(e));this.c.addEventListener('pointermove',e=>this.move(e));window.addEventListener('pointerup',()=>this.up());$$('[data-persp]').forEach(b=>b.onclick=()=>{this.mode=b.dataset.persp;$$('[data-persp]').forEach(x=>x.classList.toggle('active',x===b));this.draw();});$$('[data-tool]').forEach(b=>b.onclick=()=>{this.tool=b.dataset.tool;$$('[data-tool]').forEach(x=>x.classList.toggle('active',x===b));});$('#undo').onclick=()=>{this.strokes.pop();this.draw();};['density','alpha','brush','penColor'].forEach(id=>$('#'+id).oninput=()=>this.draw());$('#clearPad').onclick=()=>{this.strokes=[];this.ref=null;this.draw();};$('#savePng').onclick=()=>{const a=document.createElement('a');a.download='drawescape-perspective.png';a.href=this.c.toDataURL('image/png');a.click();};$('#refUpload').onchange=e=>{const file=e.target.files[0];if(!file)return;const img=new Image();img.onload=()=>{this.ref=img;this.draw();};img.src=URL.createObjectURL(file);};}
 resize(){const r=resizeCanvas(this.c);this.w=r.w;this.h=r.h;if(!this._scaled){this.vps.left={x:this.w*.18,y:this.h*.46,c:'#55bfd5'};this.vps.right={x:this.w*.82,y:this.h*.47,c:'#9287e8'};this.vps.top={x:this.w*.5,y:this.h*.12,c:'#ffd166'};this.horizon=this.h*.47;this._scaled=true;}this.draw();}
 nearVp(x,y){for(const k of Object.keys(this.vps)){const p=this.vps[k];if((p.x-x)**2+(p.y-y)**2<400)return k;}return null;}
 down(e){const r=this.c.getBoundingClientRect(),x=e.clientX-r.left,y=e.clientY-r.top;const vp=this.nearVp(x,y);if(vp){this.dragVp=vp;return;}if(this.tool==='move')return;this.current={color:$('#penColor').value,size:+$('#brush').value,erase:this.tool==='erase',pts:[{x,y}]};}
 move(e){const r=this.c.getBoundingClientRect(),x=e.clientX-r.left,y=e.clientY-r.top;if(this.dragVp){this.vps[this.dragVp].x=x;this.vps[this.dragVp].y=y;if(this.dragVp==='left'||this.dragVp==='right')this.horizon=(this.vps.left.y+this.vps.right.y)/2;this.draw();return;}if(this.current){this.current.pts.push({x,y});this.draw();}}
 up(){if(this.current){this.strokes.push(this.current);this.current=null;this.draw();}this.dragVp=null;}
 drawGrid(){const ctx=this.ctx,d=+$('#density').value,a=+$('#alpha').value/100;ctx.save();ctx.globalAlpha=a;ctx.strokeStyle='#55bfd5';ctx.lineWidth=1;const modes=this.mode==='1p'?['right']:this.mode==='2p'?['left','right']:['left','right','top'];modes.forEach(m=>{const vp=this.vps[m];ctx.strokeStyle=vp.c;for(let i=0;i<=d;i++){const x=this.w*(i/d);ctx.beginPath();ctx.moveTo(x,this.h);ctx.lineTo(vp.x,vp.y);ctx.stroke();}for(let i=1;i<d;i++){const y=this.h*.35+i*i*(this.h*.58)/(d*d);ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(this.w,y);ctx.stroke();}});ctx.strokeStyle='rgba(36,49,58,.34)';ctx.setLineDash([8,8]);ctx.beginPath();ctx.moveTo(0,this.horizon);ctx.lineTo(this.w,this.horizon);ctx.stroke();ctx.restore();}
 drawStrokes(){const ctx=this.ctx;const all=this.current?[...this.strokes,this.current]:this.strokes;all.forEach(s=>{ctx.save();ctx.strokeStyle=s.erase?'#fffdf8':s.color;ctx.lineWidth=s.size;ctx.lineCap='round';ctx.lineJoin='round';ctx.globalCompositeOperation=s.erase?'destination-out':'source-over';ctx.beginPath();s.pts.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.stroke();ctx.restore();});}
 drawVps(){const ctx=this.ctx;Object.entries(this.vps).forEach(([k,p])=>{if(this.mode==='1p'&&k!=='right')return;if(this.mode==='2p'&&k==='top')return;ctx.save();ctx.fillStyle=p.c;ctx.strokeStyle='#fff';ctx.lineWidth=3;ctx.beginPath();ctx.arc(p.x,p.y,11,0,TAU);ctx.fill();ctx.stroke();ctx.fillStyle='#24313a';ctx.font='12px '+getComputedStyle(document.body).fontFamily;ctx.fillText(k,p.x+14,p.y-10);ctx.restore();});}
 draw(){if(!this.ctx)return;const ctx=this.ctx;ctx.clearRect(0,0,this.w,this.h);ctx.fillStyle='#fffdf8';ctx.fillRect(0,0,this.w,this.h);if(this.ref){const s=Math.min(this.w/this.ref.width,this.h/this.ref.height);const iw=this.ref.width*s,ih=this.ref.height*s;ctx.globalAlpha=.35;ctx.drawImage(this.ref,(this.w-iw)/2,(this.h-ih)/2,iw,ih);ctx.globalAlpha=1;}this.drawGrid();this.drawStrokes();this.drawVps();}
}
const perspPad=new PerspectivePad();

const colorLab={inited:false,ensure(){if(this.inited){this.render();return;}this.inited=true;['baseColor','sat','val'].forEach(id=>$('#'+id).oninput=()=>this.render());this.render();},render(){const base=$('#baseColor').value;let hsl=rgbToHsl(...Object.values(hexToRgb(base)));hsl.s=+$('#sat').value;hsl.l=+$('#val').value;const pal=[['固有色',hslHex(hsl.h,hsl.s,hsl.l)],['亮部',hslHex(hsl.h-8,Math.max(20,hsl.s-12),Math.min(94,hsl.l+15))],['暗部',hslHex(hsl.h+18,Math.max(18,hsl.s-8),Math.max(20,hsl.l-28))],['环境反光',hslHex(hsl.h+160,Math.max(24,hsl.s-18),Math.min(84,hsl.l+4))],['互补色',hslHex(hsl.h+180,hsl.s,Math.max(42,hsl.l-4))],['邻近色',hslHex(hsl.h+32,hsl.s,Math.min(88,hsl.l+2))]];$('#swatches').innerHTML=pal.map(([n,c])=>`<div class="swatch" style="background:${c}"><span>${n}</span><span>${c}</span></div>`).join('');$('#paletteExplain').textContent='调色逻辑：先确定固有色，再把光照、环境、暗部和高光拆成不同通道。这样颜色不会散，每一块颜色都有原因。';$('#colorLessons').innerHTML=[['固有色','物体在中性光下的基础身份。'],['亮部','被光照到的面，通常更亮、更接近光源色。'],['暗部','背光面，不只是加黑，常带环境色。'],['环境反光','周围物体或天空反射进暗部的颜色。'],['高光','表面反射光源的位置，粗糙度决定形状。']].map(x=>`<div class="lesson"><b>${x[0]}</b><small>${x[1]}</small></div>`).join('');this.drawSphere(pal);},drawSphere(pal){const c=$('#colorSphere'),ctx=c.getContext('2d');const r=resizeCanvas(c);const w=r.w,h=r.h;ctx.clearRect(0,0,w,h);const cx=w/2,cy=h/2,rad=Math.min(w,h)*.34;const g=ctx.createRadialGradient(cx-rad*.38,cy-rad*.42,rad*.06,cx,cy,rad);g.addColorStop(0,'#fff');g.addColorStop(.16,pal[1][1]);g.addColorStop(.62,pal[0][1]);g.addColorStop(1,pal[2][1]);ctx.fillStyle=g;ctx.beginPath();ctx.arc(cx,cy,rad,0,TAU);ctx.fill();ctx.strokeStyle='rgba(36,49,58,.25)';ctx.lineWidth=2;ctx.stroke();ctx.fillStyle=pal[3][1];ctx.globalAlpha=.35;ctx.beginPath();ctx.ellipse(cx+rad*.35,cy+rad*.2,rad*.25,rad*.12,.5,0,TAU);ctx.fill();ctx.globalAlpha=1;ctx.fillStyle=pal[4][1];ctx.beginPath();ctx.arc(cx-rad*.25,cy-rad*.33,rad*.075,0,TAU);ctx.fill();}}

class FlowLab{constructor(){this.inited=false;this.type='wind';this.force={x:360,y:230};this.p=[];this.drag=false;}ensure(){if(this.inited){this.resize();return;}this.inited=true;this.c=$('#flowCanvas');this.ctx=this.c.getContext('2d');this.bind();this.resize();this.reset();this.loop();}bind(){window.addEventListener('resize',()=>this.resize());this.c.addEventListener('pointerdown',e=>{const p=this.pos(e);this.drag=true;this.force=p;});this.c.addEventListener('pointermove',e=>{if(this.drag)this.force=this.pos(e);});window.addEventListener('pointerup',()=>this.drag=false);$$('[data-flow]').forEach(b=>b.onclick=()=>{this.type=b.dataset.flow;$$('[data-flow]').forEach(x=>x.classList.toggle('active',x===b));this.reset();this.updatePrinciple();});['flowStrength','flowDensity','flowNoise'].forEach(id=>$('#'+id).oninput=()=>this.reset());}pos(e){const r=this.c.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top};}resize(){const r=resizeCanvas(this.c);this.w=r.w;this.h=r.h;this.reset();}reset(){const n=+$('#flowDensity').value||120;this.p=Array.from({length:n},()=>({x:Math.random()*this.w,y:Math.random()*this.h,px:0,py:0,life:Math.random()*100}));}updatePrinciple(){const m={wind:'风不可见，要通过飘带、头发、树叶、烟等可见证据表达方向。',water:'水绕过障碍物时会形成加速、分流和涡流；画水常画流线和泡沫。',smoke:'烟是上升、扩散、被风拉伸的密度云。边缘要破碎，不要画成硬轮廓。',rain:'雨由重力和风共同决定方向，密度和节奏比单根雨线更重要。'};$('#flowPrinciple').textContent=m[this.type];}
 field(x,y){const s=(+$('#flowStrength').value)/100;const noise=(+$('#flowNoise').value)/100;let dx=(this.force.x-this.w/2)/this.w*2,dy=(this.force.y-this.h/2)/this.h*2;if(this.type==='water'){const ox=this.w*.52,oy=this.h*.54;const vx=x-ox,vy=y-oy,d=Math.max(40,Math.hypot(vx,vy));dx=1.2*s + (-vy/d)*0.7*s*(120/d);dy=(vy/d)*.1 + (vx/d)*0.7*s*(120/d);}else if(this.type==='smoke'){dx=dx*.45*s + Math.sin(y*.025)*noise*.5;dy=-.9*s - .25;}else if(this.type==='rain'){dx=dx*.65*s;dy=1.9*s+.8;}else{dx=dx*1.5*s + Math.sin(y*.02)*noise*.35;dy=dy*1.2*s + Math.cos(x*.018)*noise*.25;}return {dx,dy};}
 loop(){const ctx=this.ctx;if(!ctx)return;ctx.fillStyle=document.body.classList.contains('theme-night')?'rgba(16,24,39,.18)':'rgba(255,253,248,.22)';ctx.fillRect(0,0,this.w,this.h);if(this.type==='water'){ctx.save();ctx.fillStyle='rgba(36,49,58,.18)';ctx.beginPath();ctx.arc(this.w*.52,this.h*.54,52,0,TAU);ctx.fill();ctx.restore();}ctx.save();ctx.strokeStyle=this.type==='rain'?'rgba(85,191,213,.50)':this.type==='smoke'?'rgba(104,119,130,.38)':'rgba(71,183,219,.48)';ctx.lineWidth=this.type==='rain'?1.2:1.6;ctx.lineCap='round';this.p.forEach(p=>{const f=this.field(p.x,p.y);p.px=p.x;p.py=p.y;p.x+=f.dx*(this.type==='rain'?4:2.2);p.y+=f.dy*(this.type==='rain'?4:2.2);p.life--;if(p.x<0||p.x>this.w||p.y<0||p.y>this.h||p.life<0){p.x=Math.random()*this.w;p.y=this.type==='smoke'?this.h+Math.random()*30:Math.random()*this.h;p.life=60+Math.random()*120;}ctx.beginPath();ctx.moveTo(p.px,p.py);ctx.lineTo(p.x,p.y);ctx.stroke();});ctx.restore();ctx.save();ctx.fillStyle='#ffd166';ctx.strokeStyle='#fff';ctx.lineWidth=3;ctx.beginPath();ctx.arc(this.force.x,this.force.y,13,0,TAU);ctx.fill();ctx.stroke();ctx.fillStyle='#24313a';ctx.font='12px '+getComputedStyle(document.body).fontFamily;ctx.fillText('force',this.force.x+16,this.force.y-12);ctx.restore();requestAnimationFrame(()=>this.loop());}}
const flowLab=new FlowLab();

function init(){initNav();sky.start();portal.start();renderMap();renderQuests();renderSources();showPage(state.page||'home');}
window.addEventListener('DOMContentLoaded',init);
